core.entity_form_display.paragraph.d_p_block.default:
  add:
    dependencies:
      module:
        - field_group
    third_party_settings:
      field_group:
        group_tabs:
          children:
            - group_basic
            - group_settings
          parent_name: ''
          weight: 0
          format_type: tabs
          region: content
          format_settings:
            id: ''
            classes: ''
            direction: horizontal
          label: Tabs
        group_basic:
          children:
            - field_block
          parent_name: group_tabs
          weight: 5
          format_type: tab
          region: content
          format_settings:
            id: ''
            classes: ''
            description: ''
            formatter: open
            required_fields: true
          label: Basic
        group_settings:
          children:
            - field_d_settings
          parent_name: group_tabs
          weight: 6
          format_type: tab
          region: content
          format_settings:
            id: ''
            classes: ''
            description: ''
            formatter: closed
            required_fields: true
          label: Settings

  change:
    expected:
      content:
        field_block:
          weight: 0
        field_d_settings:
          weight: 1
    new:
      content:
        field_block:
          weight: 1
        field_d_settings:
          weight: 7
