field.field.paragraph.d_p_reference_content.field_d_cta_link:
  delete:
    - default_value
  add:
    default_value:
      -
        options:
          attributes:
            class: 'btn btn-primary'
