core.entity_view_display.paragraph.d_p_side_image.default:
  delete:
    - hidden:field_d_p_si_image_side
  delete_value:
    - parents: dependencies:config
      values:
        - field.field.paragraph.d_p_side_image.field_d_p_si_image_side
core.entity_form_display.paragraph.d_p_side_image.default:
  delete:
    - content:field_d_p_si_image_side
  delete_value:
    - parents: dependencies:config
      values:
        - field.field.paragraph.d_p_side_image.field_d_p_si_image_side
