core.entity_form_display.paragraph.d_p_group_of_counters.default:
  add:
    dependencies:
      config:
        - field.field.paragraph.d_p_group_of_counters.field_d_cta_link
        - field.field.paragraph.d_p_group_of_counters.field_d_long_text
      module:
        - link_attributes
        - text
    content:
      field_d_cta_link:
        weight: 7
        settings:
          placeholder_url: ''
          placeholder_title: ''
          enabled_attributes:
            id: true
            name: true
            target: true
            rel: true
            class: true
            accesskey: true
            aria-label: false
            title: false
        third_party_settings: {  }
        type: link_attributes
        region: content
      field_d_long_text:
        weight: 4
        settings:
          rows: 5
          placeholder: ''
        third_party_settings: {  }
        type: text_textarea
        region: content
  change:
    expected:
      content:
        field_d_media_background:
          weight: 4
    new:
      content:
        field_d_media_background:
          weight: 3
core.entity_view_display.paragraph.d_p_group_of_counters.default:
  add:
    dependencies:
      config:
        - field.field.paragraph.d_p_group_of_counters.field_d_cta_link
        - field.field.paragraph.d_p_group_of_counters.field_d_long_text
      module:
        - link
        - text
    third_party_settings:
      field_group:
        group_d_counters_content:
          children:
            - field_d_long_text
            - field_d_cta_link
    content:
      field_d_cta_link:
        weight: 9
        label: hidden
        settings:
          trim_length: 80
          url_only: false
          url_plain: false
          rel: ''
          target: ''
        third_party_settings: {  }
        type: link
        region: content
      field_d_long_text:
        weight: 7
        label: hidden
        settings: {  }
        third_party_settings: {  }
        type: text_default
        region: content
  change:
    expected:
      content:
        field_d_counter_reference:
          weight: 7
    new:
      content:
        field_d_counter_reference:
          weight: 8
core.entity_form_display.paragraph.d_p_single_counter.default:
  add:
    dependencies:
      config:
        - field.field.paragraph.d_p_single_counter.field_d_media_icon
    content:
      field_d_media_icon:
        weight: 3
        settings:
          media_types: {  }
        third_party_settings: {  }
        type: media_library_widget
        region: content
core.entity_view_display.paragraph.d_p_single_counter.default:
  add:
    dependencies:
      config:
        - field.field.paragraph.d_p_single_counter.field_d_media_icon
    content:
      field_d_media_icon:
        weight: 0
        label: hidden
        settings:
          view_mode: d_icon
          link: false
        third_party_settings: {  }
        type: entity_reference_entity_view
        region: content
  change:
    expected:
      content:
        field_d_main_title:
          weight: 1
        field_d_number:
          weight: 0
    new:
      content:
        field_d_main_title:
          weight: 2
        field_d_number:
          weight: 1
