core.entity_view_display.media.d_image.carousel_item:
  add:
    dependencies:
      module:
        - lazy
core.entity_view_display.media.d_image.counter:
  add:
    dependencies:
      module:
        - lazy
core.entity_view_display.media.d_image.d_icon:
  add:
    dependencies:
      module:
        - lazy
core.entity_view_display.media.d_image.d_tiles_gallery_fullscreen:
  add:
    dependencies:
      module:
        - lazy
core.entity_view_display.media.d_image.default:
  add:
    dependencies:
      module:
        - lazy
core.entity_view_display.media.d_image.full:
  add:
    dependencies:
      module:
        - lazy
core.entity_view_display.media.d_image.gallery_item:
  add:
    dependencies:
      module:
        - lazy
core.entity_view_display.media.d_image.d_banner:
  add:
    dependencies:
      module:
        - lazy
core.entity_view_display.media.d_image.d_responsive_background:
  add:
    dependencies:
      module:
        - lazy
