views.view.product_images:
  change:
    expected:
      base_table: node_field_data
      base_field: nid
      display:
        default:
          display_options:
            filters:
              status:
                table: node_field_data
            sorts:
              created:
                table: node_field_data
    new:
      base_table: node_field_revision
      base_field: vid
      display:
        default:
          display_options:
            filters:
              status:
                table: node_field_revision
            sorts:
              created:
                table: node_field_revision
  delete:
    - display:default:display_options:arguments:nid
  add:
    display:
      default:
        display_options:
          arguments:
            vid:
              id: vid
              table: node_field_revision
              field: vid
              relationship: none
              group_type: group
              admin_label: ''
              default_action: default
              exception:
                value: all
                title_enable: false
                title: All
              title_enable: false
              title: ''
              default_argument_type: node
              default_argument_options: {  }
              default_argument_skip_url: false
              summary_options:
                base_path: ''
                count: true
                items_per_page: 25
                override: false
              summary:
                sort_order: asc
                number_of_records: 0
                format: default_summary
              specify_validation: false
              validate:
                type: none
                fail: 'not found'
              validate_options: {  }
              break_phrase: false
              not: false
              entity_type: node
              entity_field: vid
              plugin_id: node_vid

core.entity_view_display.node.d_product.default:
  delete:
    - content:field_d_product_media:third_party_settings:lazy

core.entity_view_display.node.d_product.teaser:
  delete:
    - content:field_d_product_media:third_party_settings:lazy
