core.entity_form_display.paragraph.d_p_gallery.default:
  add:
    content:
      field_d_settings:
        settings:
          filter_mode: '1'
          allowed_settings:
            heading_type:
              status: '1'
            custom_class:
              status: '1'
              modifiers:
                padding-bottom:
                  status: '1'
                paragraph-theme:
                  status: '1'
                margin-bottom:
                  status: '1'
                margin-top:
                  status: '1'
                padding-top:
                  status: '1'
                stripe-sidebar:
                  status: 0
                tile:
                  status: 0
                with-divider:
                  status: 0
                with-tiles:
                  status: 0
                half-transparent:
                  status: 0
                with-grid:
                  status: 0
                with-price:
                  status: 0
                header-into-columns:
                  status: 0
                full-width:
                  status: 0
            side_image_layout:
              status: 0
            column_count_tablet:
              status: 0
            form_layout:
              status: 0
            side_tiles_layout:
              status: 0
            featured_images:
              status: 0
            column_count_mobile:
              status: 0
            embed_layout:
              status: 0
            column_count:
              status: 0
